version: '3.9'
services:
  node:
    container_name: node-${NODE_VERSION:-latest}
    image: dev-node:${NODE_VERSION:-latest}
    build: 
      context: ./node
      args: 
        - NODE_VERSION=${NODE_VERSION}
        - NODE_UID=${NODE_UID}
        - NODE_GID=${NODE_GID}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
        - dev-build
networks:
    dev-build:
        name: dev-build