version: '3'
services:
    php80:
        build:
            context: ./php/php-80
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-php80
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${PHP_PORT:-9000}:9000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${PHP_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './project:/var/www/html'
        networks:
            - dev-build
networks:
    dev-build:
        name: dev-build